assets:
  ADAEUR
  ALGOEUR
  ATOMEUR
  BALEUR
  BATEUR
  BCHEUR
  COMPEUR
  CRVEUR
  DAIEUR
  DASHEUR
  DOTEUR
  EOSEUR
  FILEUR
  GNOEUR
  ICXEUR
  KAVAEUR
  KNCEUR
  KSMEUR
  LINKEUR
  LSKEUR
  NANOEUR
  OMGEUR
  OXTEUR
  PAXGEUR
  QTUMEUR
  REPV2EUR
  SCEUR
  SNXEUR
  STORJEUR
  TRXEUR
  UNIEUR
  USDCEUR
  USDTEUR
  WAVESEUR
  XDGEUR
  ETCEUR
  ETHEUR
  LTCEUR
  MLNEUR
  REPEUR
  XTZEUR
  XBTEUR
  XLMEUR
  XMREUR
  XRPEUR
  ZECEUR
  YFIEUR
